os: osx
osx_image: xcode9.2

services:
  - mysql
  - postgresql

language: node_js
node_js:
  - "8.9.4"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/Library/Caches/Yarn/v1

script:
  - yarn run lint
  - yarn run test
