version: 2
jobs:
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.9.4-browsers
        environment:
          - MYSQL_USER=bdash
          - MYSQL_DATABASE=bdash_test
          - POSTGRES_USER=bdash
          - POSTGRES_DB=bdash_test
      - image: mysql:5.6
        environment:
          - MYSQL_USER=bdash
          - MYSQL_DATABASE=bdash_test
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=bdash
          - POSTGRES_DB=bdash_test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.electron
            - ~/.cache/yarn

workflows:
  version: 2
  workflow:
    jobs:
      - test
